In [12]:
import numpy as np

## n_size_ndarray_creation <br>
* 함수목적 <br> 
n의 제곱수로 2 dimentional array를 생성하는 ndarray. <br>
* Args <br> 
n: 생성하고자 하는 ndarray의 row와 column의 개수 <br>
dtype: 생성하려는 ndarray의 data type (np.int) <br>
* Returns <br> 
row와 column의 길이가 n인 two dimentional ndarray로 X[0,0]은 0으로 순차적으로 X[n-1,n-1]은 n^2-1이 할당됨

In [13]:
n = 3
np.arange(n**2).reshape(n,n)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
def n_size_ndarray_creation(n, dtype=np.int):
    return np.array(range(n**2), dtype=dtype).reshape(n,n)

In [26]:
n_size_ndarray_creation(3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## zero_or_one_or_empty_ndarray <br>
* 함수목적 <br>
shape이 지정된 크기의 ndarray를 생성, 이때 행렬의 element는 type에 따라 0, 1 또는 empty로 생성됨.
* Args <br>
shape: 생성할려는 ndarray의 shape <br> 
type: 생성되는 element들의 값을 지정함 0은 0, 1은 1, 99는 empty 타입으로 생성됨 <br>
dtype: 생성하려는 ndarray의 data type (np.int)
* Returns <br>
shape의 크기로 생성된 ndarray로 type에 따라 element의 내용이 변경됨

In [29]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    if type == 0:
        return np.zeros(shape=shape, dtype=dtype)
    if type == 1:
        return np.ones(shape=shape, dtype=dtype)
    if type == 99:
        return np.empty(shape=shape, dtype=dtype)

In [34]:
zero_or_one_or_empty_ndarray((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## change_shape_of_ndarray <br>
* 함수목적 <br>
입력된 ndarray X를 n_row의 값을 row의 개수로 지정한 matrix를 반환함. <br>
이때 입력하는 X의 size는 2의 거듭제곱수로 전제함. <br>
만약 n_row과 1일 때는 matrix가 아닌 vector로 반환함. <br>
* Args <br> 
X: 입력하는 ndarray <br>
n_row: 생성할려는 matrix의 row의 개수 
* Returns <br>
row의 개수가 n_row인 Matrix 또는 Vector <br>
n_row가 1이면 Vector 값으로 반환함

In [36]:
def change_shape_of_ndarray(X, n_row):
    return X.flatten() if n_row==1 else X.reshape(n_row, -1) # -1은 데이터 사이즈에 남은 부분 column선정

X = np.ones((32,32), dtype=np.int)
change_shape_of_ndarray(X,1)

array([1, 1, 1, ..., 1, 1, 1])

## concat_ndarray <br>
* 함수목적 <br>
입력된 ndarray X_1과 X_2를 axis로 입력된 축을 기준으로 통합하여 반환하는 함수 <br>
X_1과 X_2는 matrix 또는 vector 임, 그러므로 vector 일 경우도 처리할 수 가 있어야 함 <br>
axis를 기준으로 통합할 때, 통합이 불가능하면 False가 반환됨. <br>
단 X_1과 X_2 Matrix, Vector 형태로 들어왔다면, Vector를 row가 1개인 Matrix로 변환하여 통합이 가능한지 확인할 것
* Args <br>
X_1: 입력하는 ndarray <br>
X_2: 입력하는 ndarray <br>
axis: 통합의 기준이 되는 축 0 또는 1임 <br>
* Returns <br>
X_1과 X_2과 통합된 matrix 타입의 ndarray

In [38]:
def concat_ndarray(X_1, X_2, axis):
    try:
        if X_1.ndim == 1:
            X_1 = X_1.reshape(1, -1)
        if X_2.ndim == 1:
            X_2 = X_2.reshape(1, -1)
        return np.concatenate((X_1, X_2), axis=axis)
    except ValueError as e:
        return False

a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
concat_ndarray(a, b, 1) 

False

## nomalize_ndarray <br>
* 함수목적 <br>
입력된 Matrix 또는 Vector를 ndarray X의 정규화된 값으로 변환하여 반환함 <br>
이때 정규화 변환 공식 Z = (X - X의평균) / X의 표준편차로 구성됨. <br>
X의 평균과 표준편차는 axis를 기준으로 axis 별로 산출됨. <br>
Matrix의 경우 axis가 0 또는 1일 경우, row 또는 column별로 Z value를 산출함. <br>
axis가 99일 경우 전체 값에 대한 normalize 값을 구함.<br> 
* Args <br>
X: 입력하는 ndarray, <br>
axis: normalize를 구하는 기준이 되는 축으로 0, 1 또는 99임, 단 99는 axis 구분 없이 전체값으로 평균과 표준편차를 구함 <br>
dtype: data type으로 np.float32로 구정 <br>
* Returns <Br> 
정규화된 ndarray

In [40]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    X = X.astype(np.float32)
    n_row, n_column = X.shape # 원소를 tuple 형태로 뽑아냄
    if axis == 99:
        x_mean = np.mean(X)
        x_str = np.std(X)
        Z = (X - x_mean) / x_std
    if axis == 0:
        x_mean = np.mean(X, 0).reshape(1, -1)
        x_std = np.std(X, 0).reshape(1, -1)
        Z = (X - x_mean) / x_std
    if axis == 1:
        x_mean = np.mean(X, 1).reshape(n_row, -1)
        x_std = np.std(X, 1).reshape(n_row, -1)
        Z = (X - x_mean) / x_std
    return Z


X = np.arange(12, dtype=np.float32).reshape(4,3)
normalize_ndarray(X,1)

array([[-1.2247448,  0.       ,  1.2247448],
       [-1.2247448,  0.       ,  1.2247448],
       [-1.2247448,  0.       ,  1.2247448],
       [-1.2247448,  0.       ,  1.2247448]], dtype=float32)

## save_ndarray <Br>
* 함수목적 <br>
입력된 ndarray X를 argument filename으로 저장함 <br>
* Args <br>
X: 입력하는 ndarray <br>
filename: 저장할려는 파일이름

In [41]:
def save_ndarray(X, filename="test.npy"):
    file_test = open(filename, "wb")
    np.save(X, file_test) # pickle 형태로 저장됨

## boolean_index <br>
* 함수목적 <br>
입력된 ndarray X를 String type의 condition 정보를 바탕으로 해당 컨디션에 해당하는 ndarray X의 index 번호를 반환함<br>
단 이때, str type의 조건인 condition을 코드로 변환하기 위해서는 eval(str("X") + condition)를 사용할 수 있음 <br>
* Args <br>
X: 입력하는 ndarray <br>
condition: string type의 조건 (">3", "== 5", "< 15") <br>
* Returns <br> 
조건에 만족하는 ndarray X의 index

In [42]:
def boolean_index(X, condition):
    condition = eval(str("X") + condition)
    return np.where(condition)

X = np.arange(32, dtype=np.float32)
boolean_index(X, ">6")

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29, 30, 31], dtype=int64),)

In [43]:
np.where(X>6) # 이거 기억해야해

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29, 30, 31], dtype=int64),)

## find_nearest_value <br> 
* 함수목적 <br> 
입력된 vector type의 ndarray X에서 target_value와 가장 차이가 작게나는 element를 찾아 리턴함 <br>
이때 X를 list로 변경하여 처리하는 것은 실패로 간주함. <br>
* Args <Br>
X: 입력하는 vector type의 ndarray <br>
target_value : 가장 유사한 값의 기준값이 되는 값 <br>
* Returns <br>
target_value와 가장 유사한 값

In [59]:
def find_nearest_value(X, target_value):
    return X[np.argmin(np.abs(X-target_value))]

X = np.random.uniform(0, 1, 5)
target_value = 0.3
print(X)
print(np.abs(X-target_value))

[0.028512   0.87739807 0.81780059 0.08319128 0.31670749]
[0.271488   0.57739807 0.51780059 0.21680872 0.01670749]


In [60]:
find_nearest_value(X, target_value)

0.3167074946621192

## get_n_largest_values
* 함수목적 <br>
입력된 vector type의 ndarray X에서 큰 숫자 순서대로 n개의 값을 반환함. <br>
* Args <br>
X: vector type의 ndarray <br>
n: 반환할려는 element의 개수 <Br>
* Returns <br> 
ndarray X의 element중 큰 숫자 순서대로 n개 값이 반환됨 ndarray

In [66]:
def get_n_largest_values(X, n):
    return X[np.argsort(X[::-1])[:n]]

X = np.random.uniform(0, 1, 5)
print(X)
print(np.argsort(X)) # 작은 값으로 sorting, ::-1은 역순(큰값부터) sorting
get_n_largest_values(X,3)

[0.52154563 0.88029869 0.32256404 0.73000316 0.1614031 ]
[4 2 0 3 1]


array([0.52154563, 0.32256404, 0.1614031 ])