# Numpy <br>
* Numerical Python
* 파이썬의 고성능 과학 계산용 패키지
* Matrix와 Vector와 같은 Array 연산의 사실상 표준
* 한글로는 넘파이로 주로 통칭, 넢피/늄파이라고도 부르기도 함
* 일반 List에 비해 빠르고, 메모리 효율적
* 반복문 없이 데이터 배열에 대한 처리를 지원
* 선형대수와 관련된 다양한 기능 제공
* C, C++, 포트란 등의 언어와 통합 가능

## ndarray

## import - numpy 모듈의 호출

In [1]:
import numpy as np

* numpy의 호출 방법
* 일반적으로는 numpy는 np라는 alias(별칭) 이용해서 호출
* 특별한 이유는 없고 약속같은 것

## Array creation <br>
* numpy는 np.array 함수를 이용하여 배열을 생성 -> ndarray
* numpy는 하나의 데이터 type만 배열에 넣을 수 있음
* List와 가장 큰 차이점, Dynamic typing not supported
* C의 Array를 사용하여 배열을 생서

In [2]:
test_array = np.array(["1", "4", 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [3]:
type(test_array[3])

numpy.float64

In [4]:
test_array = np.array([1, 4, 5, "8"], np.float32) # String Type의 데이터를 입력해도
test_array

array([1., 4., 5., 8.], dtype=float32)

In [5]:
type(test_array[3])   # Float Type으로 자동 형변환을 실시

numpy.float32

In [6]:
test_array.dtype   # Array(배열) 전체의 데이터 Type을 반환함

dtype('float32')

In [7]:
np.array([[1, 4, 5, "8"]], np.float32).shape

(1, 4)

In [8]:
test_array.shape   # Array(배열) 의 shape을 반환함

(4,)

## array shape (vector) <br>
* Array(vector, matrix, tensor)의 크기, 형태 등에 대한 정보
* Shape : numpy array의 object의 dimension 구성을 반환
* dtype : numpy array의 데이터 type을 반환

In [2]:
test_array = np.array([1, 4, 5, "8"], float) # string Type의 데이터를 입력해도

print(test_array)
print(type(test_array[3]))  # Float Type으로 자동 형변환을 실시
print(test_array.dtype)     # Array(배열) 전체의 데이터 Type을 반환함
print(test_array.shape)     # Array(배열)의 Shape을 반환함

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


## Array shape (matrix)

In [3]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

## Array shape (3rd order tensor)

In [10]:
tensor  = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

## Array shape - ndim & size <br>
* ndim - number of dimensino
* size - data의 개수

In [11]:
np. array(tensor, int).ndim

3

In [12]:
np.array(tensor, int).size

48

## Array dtype <br>
* Ndarray의 single element가 가지는 data type
* 각 element가 차지하는 memory의 크기가 결정됨

In [5]:
np.array([[1, 2, 3], [4.5, 5, 6]], dtype=int) # Data type을 integer로 선언

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32) # Data type을 float로 선언

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

* nbytes - ndarray object의 메모리 크기를 반환함

In [7]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32).nbytes # 32bits = 4bytes -> 6*4 bytes

24

In [8]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.int8).nbytes # 8bits = 1bytes -> 6*1 bytes

6

In [9]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float64).nbytes # 64bits = 8bytes -> 6*8 bytes

48

# Shape Handiling

## reshape <br>
* Array의 shape의 크기를 변경함 (element의 갯수는 동일)

In [14]:
test_matrix = [[1, 2, 3, 4], [1, 2, 5, 8]]
np.array(test_matrix).shape

(2, 4)

In [15]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

* Array의 size만 같다면 다차원으로 자유로이 변형 가능

In [16]:
np.array(test_matrix).reshape(-1,2).shape # -1: size를 기반으로 row 개수를 선정

(4, 2)

## flatten ( or flat ) <br>
* 다차원 array를 1차원 array로 변환

In [17]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

# Indexing & slicing

In [18]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], int)
print(a)
print(a[0, 0]) # Two dimensional array representation #1
print(a[0][0]) # Two dimensional array representation #2

a[0, 0] = 12 # Matrix 0,0 에 12할당
print(a)
a[0][0] = 5 # Matrix 0,0 에 5 할당
print(a)

[[1 2 3]
 [4 5 6]]
1
1
[[12  2  3]
 [ 4  5  6]]
[[5 2 3]
 [4 5 6]]


* List와 달리 이차원 배열에서 [0,0]과 같은 표기법을 제공함
* Matrix 일 경우 앞은 row 뒤는 column을 의미

## slicing

In [20]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
a[:,2:] # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [21]:
a[1, 1:3] # 1 Row의 1열 ~ 2열

array([7, 8])

In [22]:
a[1:3] # 1 Row ~ 2 Row의 전체

array([[ 6,  7,  8,  9, 10]])

* List와 달리 행과 열 부분을 나눠서 slicing이 가능
* Matrix의 부분 집합을 추출할 때 유용

In [23]:
test_exmaple = np.array([
    [1, 2, 5,8], [1, 2, 5,8],[1, 2, 5,8],[1, 2, 5,8]], int)
test_exmaple[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [25]:
test_exmaple[:,1:3] 
test_exmaple[1,:2]

array([1, 2])

In [26]:
a = np.arange(100).reshape(10,10)
a[:, -1].reshape(-1,1)

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])

# creation function

## arange <br>
* array의 범위를 지정하여, 값의 list를 생성하는 명령어

In [27]:
np.arange(30) # range: List의 range와 같은 효과, integer로 0부터 29까지 배열 추출

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
np.arange(0, 5, 0.5) # floating point도 표시 가능, (시작, 끝, step)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [29]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## ones, zeros and empty <br>
### zeros - 0 으로 가득찬 ndarray 생성 <br>
* np.zeros(shape, dtype, order)

In [30]:
np.zeros(shape=(10,), dtype=np.int8) # 10 - zero vector 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [31]:
np.zeros((2,5)) # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### ones - 1로 가득찬 ndarray 생성 <br>
* np.ones(shape, dtype, order)

In [32]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [33]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### empty - shape만 주어지고 비어있는 ndarray 생성 <br>
* memory initialization 이 되지 않음

In [35]:
np.empty(shape = (10,), dtype = np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [36]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## something_like <br>
* 기존 ndarray의 shape 크기 만큼 1, 0 또는 empty array를 반환

In [38]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

## identity <br>
* 단위 행렬(i 행렬)을 생성
* n -> number of rows

In [39]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [40]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## eye <br>
* 대각선인 1인 행렬, k값의 시작 index의 변경이 가능

In [41]:
np.eye( N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.eye(3,5,k=2) # k -> start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## diag <Br>
* 대각 행렬의 값을 추출

In [44]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [45]:
np.diag(matrix, k=1) # k -> start index

array([1, 5])

## random sampling <br>
* 데이터 분포에 따른 sampling 으로 array를 생성

In [48]:
np.random.uniform(0,1,10).reshape(2,5) # 균등분포

array([[0.63424972, 0.50429833, 0.95967204, 0.87225849, 0.25150646],
       [0.32868876, 0.86606504, 0.34357517, 0.68399757, 0.97720994]])

In [50]:
np.random.normal(0,1,10).reshape(2,5) # 정규분포

array([[-1.0768432 ,  0.77551893, -0.70109404, -1.65838885, -0.69653079],
       [-0.64306384, -1.29842037,  1.24391649, -0.83791727,  1.71024013]])

# operation function

## sum <br>
* ndarray의 element들 간의 합을 구함, list의 sum 기능과 동일

In [51]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
test_array.sum(dtype=np.float)

55.0

## axis <br>
* 모든 operation function을 실행할 때, 기준이 되는 dimension 축

In [53]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [55]:
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [56]:
third_order_tensor.sum(axis=2) # 밑변 column 개수

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [58]:
third_order_tensor.sum(axis=1) # 높이 row 개수

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [59]:
third_order_tensor.sum(axis=0) # 깊이 (너비)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

## mean & std <br>
* ndarray의 element들 간의 평균 또는 표준 편차를 반환

In [61]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
test_array.mean(), test_array.mean(axis=0)

(6.5, array([5., 6., 7., 8.]))

In [63]:
test_array.std(), test_array.std(axis=0)

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

## Mathematical function <br>
* 그 외에도 다양한 수학 연산자 제공 (np.something 호출)
* exponential : exp, expml, exp2, log, log10, log1p, log2, power, sqrt
* trigonometrix : sin, cos, tna, acsin, arccos, atctan
* hyperbolic : sinh, cosh, tanh, acsinh, arcosh, atctanh

In [64]:
np.exp(test_array), np.sqrt(test_array)

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
        [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
        [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]),
 array([[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]))

## concatenate <br>
* Numpy array를 합치는 함수
* 위아래(수직) 합치기 : vstack
* 옆으로(수평) 합치기 : hstack

In [65]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [66]:
a = np.array([ [1], [2], [3]])
b = np.array([ [2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

* 행으로 합치기 : concatenate / axis = 0

In [74]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate( (a,b) ,axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

* 열로 합치기(오른쪽) : concatenate / axis = 1

In [76]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate( (a,b.T) , axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [77]:
a.tolist()

[[1, 2], [3, 4]]

# array operation

## Operation b/t arrays <br>
* Numpy는 array간의 기본적인 사칙 연산을 지원

In [78]:
test_a = np.array([[1, 2, 3], [4, 5, 6]], float)

In [79]:
test_a + test_a # Matrix + Matrix 연산

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [80]:
test_a - test_a # Matrix - Matrix 연산

array([[0., 0., 0.],
       [0., 0., 0.]])

In [81]:
test_a * test_a # Matrix내 element들 간 같은 위치에 있는 값들끼리 연산

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

## Element-wise operation <br>
* Array간 shape이 같을 때 일어나는 연산

In [82]:
matrix_a = np.arange(1, 13).reshape(3, 4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

## Dot product <br>
* Matrix의 기본 연산
* dot 함수 사용

In [83]:
test_a = np.arange(1, 7).reshape(2, 3)
test_b = np.arange(7, 13).reshape(3, 2)

In [84]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

## transpose <br>
* transpose 또는 T attribute 사용

In [86]:
test_a = np.arange(1, 7).reshape(2, 3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
test_a.T.dot(test_a) # Matrix 간 곱셈

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [88]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [89]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## broadcasting <br>
* Shape이 다른 배열 간 연산을 지원하는 기능

In [90]:
test_matrix = np.array([[1, 2, 3], [4, 5, 6]], float)
scalar = 3

In [91]:
test_matrix + scalar # Matrix - Scalar 덧셈

array([[4., 5., 6.],
       [7., 8., 9.]])

In [94]:
test_matrix - scalar # Matrix - Scalar 뺄셈

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [95]:
test_matrix * 5 # Matrix - Scalar 곱셈

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [96]:
test_matrix / 5 # Matrix - Scalar 나눗셈

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [97]:
test_matrix // 0.2 # Matrix - Scalar 몫

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [98]:
test_matrix ** 0.2 # Matrix - Scalar 제곱

array([[1.        , 1.14869835, 1.24573094],
       [1.31950791, 1.37972966, 1.43096908]])

* Scalar - vector 외에도 vector - matrix 간의 연산도 지원

In [104]:
test_matrix = np.arange(1, 13).reshape(4, 3)
test_vector = np.arange(10, 40, 10)
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

## Numpy performance #1 <br>
* timeit : jupyter 환경에서 코드의 퍼포먼스를 체크하는 함수

In [106]:
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result 

iternation_max = 100000000

vector = list(range(iternation_max))
scalar = 2

%timeit sclar_vector_product(scalar, vector) # for loop을 이용한 성능

14.1 s ± 776 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [107]:
%timeit [scalar * value for value in range(iternation_max)] # list comprehension을 이용한 성능
%timeit np.arange(iternation_max) * scalar # numpy를 이용한 성능

12.7 s ± 818 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
385 ms ± 10.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Numpy performance #2 <br>
* 일반적으로 속도는 아래 순
   for loop < list comprehension < numpy
* 100,000,000 번의 loop이 돌 때 약 4배 이상의 성능 차이 보임
* Numpy는 C로 구현되어 있어, 성능을 확보
* 그러나 파이썬의 가장 큰 특징인 dynamic typing을 포기
* 대용량 계산에서 가장 흔히 사용
* Concatenate 처럼 계산이 아닌, 할당에서는 연산 속도의 이점이 없음

# Comparisons

## All & Any <br>
* Array의 데이터 전부(and) 또는 일부(or)가 조건에 만족 여부 반환

In [108]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [109]:
np.any(a > 5), np.any(a < 0) # any -> 하나라도 조건에 만족한다면 true

(True, False)

In [110]:
np.all(a > 5) , np.all(a < 10) # all -> 모두가 조건에 만족한다면 true

(False, True)

## Comparison operation #1 <br>
* Numpy는 배열의 크기가 동일 할 때
* element간 비교의 결과를 Boolean type으로 반환하여 돌려줌

In [111]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [112]:
test_a == test_b

array([False, False, False])

In [114]:
(test_a > test_b).any() # any -> 하나라도 true면 true

True

## Comparison operation #2

In [115]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3) # and 조건의 condition

array([ True, False, False])

In [116]:
b = np.array([True, False, True], bool)
np.logical_not(b) # NOT 조건의 condition

array([False,  True, False])

In [117]:
c = np.array([False, True, False], bool)
np.logical_or(b, c) # OR 조건의 condition

array([ True,  True,  True])

## np.where

In [118]:
a

array([1., 3., 0.])

In [119]:
np.where(a > 0, 3, 2) # where(condition, TRUE, FALSE)

array([3, 3, 2])

In [123]:
a = np.arange(10)  # index 값 반환
np.where(a > 5)

(array([6, 7, 8, 9], dtype=int64),)

In [121]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a) # Not a Number

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [124]:
np.isfinite(a) # is finite number

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## argmax & argmin <br>
* array내 최대값 또는 최소값의 index를 반환

In [126]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a) , np.argmin(a)

(5, 0)

* axis 기반의 반환

In [127]:
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1) , np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

# boolean & fancy index

## boolean index <br>
* numpy는 배열은 특정 조건에 따른 값을 배열 형태로 추출 할 수 있음
* Comparison operation 함수들도 모두 사용 가능

In [128]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [129]:
test_array[test_array > 3] # 조건이 True인 index의 element만 추출

array([4., 8., 9., 7.])

In [130]:
condition = test_array < 3 
test_array[condition]

array([1., 0., 2.])

In [131]:
A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])
B = A < 15
B.astype(np.int)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

## facny index <br>
* numpy는 array를 index value로 사용해서 값을 추출하는 방법

In [134]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int) # 반드시 integer로 선언
a[b] # bracket index, b 배열의 값을 index로 하여 a의 값들을 추출

array([2., 2., 4., 8., 6., 4.])

In [135]:
a.take(b) # take 함수 : bracket idnex와 같은 효과

array([2., 2., 4., 8., 6., 4.])

* Matrix 형태의 데이터도 가능

In [136]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c] # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])

In [137]:
a = np.array([[1, 4], [9, 16]], float)
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])

# numpy data i/o

## loadtxt & savetxt <br>
* Text type의 데이터를 읽고, 저장하는 기능

In [ ]:
# 파일 호출
a = np.loadtxt("./populations.txt")
a[:10]

In [ ]:
# int type 변환
a_int = a.astype(int)
a_int[:3]

In [ ]:
# int_data.csv 저장
np.savetxt('int_data.csv',a_int, delimiter=",")

## numpy object - npy <br>
* Numpy object (pickle) 형태로 데이터를 저장하고 불러옴
* Binary 파일 형태로 저장

In [ ]:
np.save("npy_test", arr=a_int)

In [ ]:
npy_array = np.load(file="npy_test.npy")
npy_array[:3]